"""Promotion report: compare strategy vs benchmark and suggest safe to deploy vs hold."""

from pathlib import Path
from typing import Any


def write_promotion_report(
    metrics: dict[str, Any],
    fold_results: list[dict[str, Any]],
    output_path: Path,
    *,
    min_sharpe: float = 0.5,
    max_drawdown_pct: float = 20.0,
    min_hit_rate_pct: float = 45.0,
    require_positive_excess: bool = True,
) -> str:
    """Write a text report: metrics summary, vs benchmark, and recommendation.

    Returns:
        Recommendation: "safe to deploy" or "hold".
    """
    lines: list[str] = []
    lines.append("# Backtest Promotion Report")
    lines.append("")
    lines.append("## Aggregate metrics (walk-forward)")
    lines.append("")
    for k, v in sorted(metrics.items()):
        if v is not None and isinstance(v, (int, float)):
            lines.append(f"- {k}: {v:.4f}" if isinstance(v, float) else f"- {k}: {v}")
    lines.append("")
    lines.append("## Per-fold summary")
    lines.append("")
    for r in fold_results:
        lines.append(f"### Fold {r['fold_id']} ({r['test_start']} to {r['test_end']})")
        for k, v in (r.get("metrics") or {}).items():
            if v is not None:
                lines.append(f"- {k}: {v}")
        lines.append("")
    lines.append("## Recommendation")
    lines.append("")

    sharpe = metrics.get("sharpe_mean") or metrics.get("sharpe")
    max_dd = metrics.get("max_drawdown_pct_mean") or metrics.get("max_drawdown_pct")
    hit_rate = metrics.get("hit_rate_pct_mean") or metrics.get("hit_rate_pct")
    excess = metrics.get("excess_return_vs_benchmark_mean") or metrics.get("excess_return_vs_benchmark")

    checks = []
    if sharpe is not None:
        checks.append(("Sharpe >= {min_sharpe}", sharpe >= min_sharpe, f"Sharpe {sharpe:.3f}"))
    if max_dd is not None:
        checks.append(("Max drawdown <= {max_dd}%", max_dd <= max_drawdown_pct, f"Max DD {max_dd:.1f}%"))
    if hit_rate is not None:
        checks.append(("Hit rate >= {min_hit}%", hit_rate >= min_hit_rate_pct, f"Hit rate {hit_rate:.1f}%"))
    if require_positive_excess and excess is not None:
        checks.append(("Excess return vs benchmark > 0", excess > 0, f"Excess {excess:.2f}%"))

    all_pass = all(passed for _, passed, _ in checks)
    recommendation = "safe to deploy" if all_pass else "hold"
    lines.append(f"**{recommendation.upper()}**")
    lines.append("")
    for (desc, passed, detail) in checks:
        status = "PASS" if passed else "FAIL"
        lines.append(f"- [{status}] {detail}")
    lines.append("")
    lines.append("---")
    lines.append("*Report generated by backtesting promotion report*")

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return recommendation
