"""add queue_status to opportunity_queue

Revision ID: 08c0df3b2af8
Revises: h1i2j3k4l5m6
Create Date: 2026-03-21 08:19:53.750429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c0df3b2af8'
down_revision: Union[str, Sequence[str], None] = 'h1i2j3k4l5m6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunity_queue', sa.Column('queue_status', sa.String(length=20), nullable=False, server_default='QUEUED'))
    op.drop_index(op.f('ix_runs_cycle_id'), table_name='runs')
    op.create_index(op.f('ix_runs_cycle_id'), 'runs', ['cycle_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_cycle_id'), table_name='runs')
    op.create_index(op.f('ix_runs_cycle_id'), 'runs', ['cycle_id'], unique=False)
    op.drop_column('opportunity_queue', 'queue_status')
    # ### end Alembic commands ###
