"""add macro_headlines table

Revision ID: 3b65184f7a11
Revises: k6l7m8n9o0p1
Create Date: 2026-03-23 18:42:48.797263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b65184f7a11'
down_revision: Union[str, Sequence[str], None] = 'k6l7m8n9o0p1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_headlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('cycle_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_headlines_category'), 'macro_headlines', ['category'], unique=False)
    op.create_index('ix_macro_headlines_dedup', 'macro_headlines', ['headline', 'published_at'], unique=True)
    op.create_index(op.f('ix_macro_headlines_published_at'), 'macro_headlines', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macro_headlines_published_at'), table_name='macro_headlines')
    op.drop_index('ix_macro_headlines_dedup', table_name='macro_headlines')
    op.drop_index(op.f('ix_macro_headlines_category'), table_name='macro_headlines')
    op.drop_table('macro_headlines')
    # ### end Alembic commands ###
