"""add_dashboard_tables

Revision ID: 45bf123ae39b
Revises: a566f7a38bc7
Create Date: 2026-03-09 15:54:25.325992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bf123ae39b'
down_revision: Union[str, Sequence[str], None] = 'a566f7a38bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _drop_index_if_exists(connection, index_name: str) -> None:
    """Drop index only if it exists (SQLite-compatible)."""
    try:
        connection.execute(sa.text(f"DROP INDEX IF EXISTS {index_name}"))
    except Exception:
        pass


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes only if they exist (schema may vary; e.g. notification_logs created without these)
    conn = op.get_bind()
    _drop_index_if_exists(conn, "ix_notification_logs_channel_timestamp")
    _drop_index_if_exists(conn, "ix_notification_logs_event_type_timestamp")
    try:
        op.drop_index(op.f('ix_trade_outcomes_sell_order_id'), table_name='trade_outcomes')
    except Exception:
        pass
    try:
        conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_trade_outcomes_sell_order_id ON trade_outcomes(sell_order_id)"))
    except Exception:
        pass

    # Dashboard tables (IF NOT EXISTS so safe when tables were already created by dashboard init)
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS events_log (
            id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
            timestamp DATETIME NOT NULL,
            event_type VARCHAR(50) NOT NULL,
            source VARCHAR(50) NOT NULL,
            message TEXT NOT NULL,
            metadata_json JSON
        )
    """))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_events_log_timestamp ON events_log(timestamp)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_events_log_event_type ON events_log(event_type)"))

    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS runs (
            id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
            cycle_id VARCHAR(100) NOT NULL UNIQUE,
            run_type VARCHAR(20) NOT NULL,
            started_at DATETIME NOT NULL,
            completed_at DATETIME,
            status VARCHAR(20) NOT NULL,
            summary_json JSON
        )
    """))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_runs_started_at ON runs(started_at)"))
    conn.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_runs_cycle_id ON runs(cycle_id)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_cycle_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_started_at'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_events_log_event_type'), table_name='events_log')
    op.drop_index(op.f('ix_events_log_timestamp'), table_name='events_log')
    op.drop_table('events_log')
    
    op.drop_index(op.f('ix_trade_outcomes_sell_order_id'), table_name='trade_outcomes')
    op.create_index(op.f('ix_trade_outcomes_sell_order_id'), 'trade_outcomes', ['sell_order_id'], unique=1)
    op.create_index(op.f('ix_notification_logs_event_type_timestamp'), 'notification_logs', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_notification_logs_channel_timestamp'), 'notification_logs', ['channel', 'timestamp'], unique=False)
    # ### end Alembic commands ###
