"""add_dashboard_tables

Revision ID: 45bf123ae39b
Revises: a566f7a38bc7
Create Date: 2026-03-09 15:54:25.325992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bf123ae39b'
down_revision: Union[str, Sequence[str], None] = 'a566f7a38bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_channel_timestamp'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_event_type_timestamp'), table_name='notification_logs')
    op.drop_index(op.f('ix_trade_outcomes_sell_order_id'), table_name='trade_outcomes')
    op.create_index(op.f('ix_trade_outcomes_sell_order_id'), 'trade_outcomes', ['sell_order_id'], unique=False)
    
    # Dashboard tables
    op.create_table('events_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_log_timestamp'), 'events_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_log_event_type'), 'events_log', ['event_type'], unique=False)
    
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.String(length=100), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_index(op.f('ix_runs_started_at'), 'runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_runs_cycle_id'), 'runs', ['cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_cycle_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_started_at'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_events_log_event_type'), table_name='events_log')
    op.drop_index(op.f('ix_events_log_timestamp'), table_name='events_log')
    op.drop_table('events_log')
    
    op.drop_index(op.f('ix_trade_outcomes_sell_order_id'), table_name='trade_outcomes')
    op.create_index(op.f('ix_trade_outcomes_sell_order_id'), 'trade_outcomes', ['sell_order_id'], unique=1)
    op.create_index(op.f('ix_notification_logs_event_type_timestamp'), 'notification_logs', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_notification_logs_channel_timestamp'), 'notification_logs', ['channel', 'timestamp'], unique=False)
    # ### end Alembic commands ###
