"""add last_screened_at to instruments

Revision ID: 7d4dd410a38f
Revises: fdad75d2f216
Create Date: 2026-02-27 21:58:07.727461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4dd410a38f'
down_revision: Union[str, Sequence[str], None] = 'fdad75d2f216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('last_screened_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'last_screened_at')
    # ### end Alembic commands ###
