"""initial schema

Revision ID: fdad75d2f216
Revises: 
Create Date: 2026-02-23 16:42:00.511856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdad75d2f216'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_logs_timestamp'), 'api_logs', ['timestamp'], unique=False)
    op.create_table('cost_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_gbp', sa.Float(), nullable=False),
    sa.Column('cycle_id', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_logs_cycle_id'), 'cost_logs', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_cost_logs_timestamp'), 'cost_logs', ['timestamp'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('min_trade_quantity', sa.Float(), nullable=True),
    sa.Column('max_open_quantity', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_ticker'), 'instruments', ['ticker'], unique=True)
    op.create_table('market_data_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_cache_ticker'), 'market_data_cache', ['ticker'], unique=False)
    op.create_index(op.f('ix_market_data_cache_timestamp'), 'market_data_cache', ['timestamp'], unique=False)
    op.create_table('moderation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cycle_id', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('moderator', sa.String(length=50), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('growth_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('modifications_json', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_gbp', sa.Float(), nullable=True),
    sa.Column('consensus', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_cycle_id'), 'moderation_logs', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_timestamp'), 'moderation_logs', ['timestamp'], unique=False)
    op.create_table('news_sentiment_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('buzz_score', sa.Float(), nullable=True),
    sa.Column('bullish_pct', sa.Float(), nullable=True),
    sa.Column('bearish_pct', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sentiment_cache_ticker'), 'news_sentiment_cache', ['ticker'], unique=False)
    op.create_index(op.f('ix_news_sentiment_cache_timestamp'), 'news_sentiment_cache', ['timestamp'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('value_gbp', sa.Float(), nullable=True),
    sa.Column('t212_order_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('conviction', sa.Integer(), nullable=True),
    sa.Column('moderation_result', sa.String(length=20), nullable=True),
    sa.Column('risk_result', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('journal_path', sa.String(length=500), nullable=True),
    sa.Column('dedup_key', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_dedup_key'), 'orders', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_orders_t212_order_id'), 'orders', ['t212_order_id'], unique=False)
    op.create_index(op.f('ix_orders_ticker'), 'orders', ['ticker'], unique=False)
    op.create_index(op.f('ix_orders_timestamp'), 'orders', ['timestamp'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_value_gbp', sa.Float(), nullable=False),
    sa.Column('cash_gbp', sa.Float(), nullable=False),
    sa.Column('invested_gbp', sa.Float(), nullable=False),
    sa.Column('pnl_gbp', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('benchmark_value', sa.Float(), nullable=True),
    sa.Column('benchmark_pnl_pct', sa.Float(), nullable=True),
    sa.Column('alpha_pct', sa.Float(), nullable=True),
    sa.Column('num_positions', sa.Integer(), nullable=False),
    sa.Column('positions_json', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_timestamp'), 'portfolio_snapshots', ['timestamp'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cycle_id', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('proposed_action', sa.String(length=10), nullable=False),
    sa.Column('proposed_allocation_pct', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('adjusted_allocation_pct', sa.Float(), nullable=True),
    sa.Column('rules_checked_json', sa.Text(), nullable=True),
    sa.Column('triggered_rules_json', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('portfolio_state_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_decisions_cycle_id'), 'risk_decisions', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_risk_decisions_timestamp'), 'risk_decisions', ['timestamp'], unique=False)
    op.create_table('strategy_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cycle_id', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('target_allocation_pct', sa.Float(), nullable=True),
    sa.Column('conviction', sa.Integer(), nullable=True),
    sa.Column('primary_strategy', sa.String(length=50), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('growth_potential', sa.String(length=10), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('catalysts_json', sa.Text(), nullable=True),
    sa.Column('risks_json', sa.Text(), nullable=True),
    sa.Column('exit_conditions', sa.Text(), nullable=True),
    sa.Column('upside_target_pct', sa.Float(), nullable=True),
    sa.Column('stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('expected_holding_period', sa.String(length=50), nullable=True),
    sa.Column('news_sentiment_summary', sa.Text(), nullable=True),
    sa.Column('market_assessment', sa.Text(), nullable=True),
    sa.Column('portfolio_commentary', sa.Text(), nullable=True),
    sa.Column('raw_response_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_decisions_cycle_id'), 'strategy_decisions', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_strategy_decisions_timestamp'), 'strategy_decisions', ['timestamp'], unique=False)
    op.create_table('system_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('peak_portfolio_value', sa.Float(), nullable=True),
    sa.Column('current_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('last_cycle_at', sa.DateTime(), nullable=True),
    sa.Column('daily_loss_halt_until', sa.DateTime(), nullable=True),
    sa.Column('paused', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_state')
    op.drop_index(op.f('ix_strategy_decisions_timestamp'), table_name='strategy_decisions')
    op.drop_index(op.f('ix_strategy_decisions_cycle_id'), table_name='strategy_decisions')
    op.drop_table('strategy_decisions')
    op.drop_index(op.f('ix_risk_decisions_timestamp'), table_name='risk_decisions')
    op.drop_index(op.f('ix_risk_decisions_cycle_id'), table_name='risk_decisions')
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_portfolio_snapshots_timestamp'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_orders_timestamp'), table_name='orders')
    op.drop_index(op.f('ix_orders_ticker'), table_name='orders')
    op.drop_index(op.f('ix_orders_t212_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_dedup_key'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_news_sentiment_cache_timestamp'), table_name='news_sentiment_cache')
    op.drop_index(op.f('ix_news_sentiment_cache_ticker'), table_name='news_sentiment_cache')
    op.drop_table('news_sentiment_cache')
    op.drop_index(op.f('ix_moderation_logs_timestamp'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_cycle_id'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    op.drop_index(op.f('ix_market_data_cache_timestamp'), table_name='market_data_cache')
    op.drop_index(op.f('ix_market_data_cache_ticker'), table_name='market_data_cache')
    op.drop_table('market_data_cache')
    op.drop_index(op.f('ix_instruments_ticker'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_cost_logs_timestamp'), table_name='cost_logs')
    op.drop_index(op.f('ix_cost_logs_cycle_id'), table_name='cost_logs')
    op.drop_table('cost_logs')
    op.drop_index(op.f('ix_api_logs_timestamp'), table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
